version: '2.2'

services:
  nextgen-eureka-server:
    image: ashoksuryap/nextgen-eureka-server
    hostname: nextgen-eureka-server
    ports:
     - "8002:8002"

  nextgen-review-service:
    image: ashoksuryap/nextgen-review-service
    hostname: nextgen-review-service
    links:
      - nextgen-eureka-server
    environment:
       EUREKA_HOST: nextgen-eureka-server
       EUREKA_PORT: 8002
    ports:
      - "8082:8082"

  nextgen-book-service:
      image: ashoksuryap/nextgen-book-service
      hostname: nextgen-book-service
      links:
        - nextgen-review-service
      environment:
         EUREKA_HOST: nextgen-eureka-server
         EUREKA_PORT: 8002
      ports:
        - "8081:8081"

  nextgen-edge-service:
    image: ashoksuryap/nextgen-edge-service
    hostname: nextgen-edge-service
    links:
      - nextgen-book-service
    environment:
       EUREKA_HOST: nextgen-eureka-server
       EUREKA_PORT: 8002
    ports:
      - "8080:8080"