version: '2.2'
service-registry:
  image: ashoksuryap/service-registry
  hostname: service-registry
  ports:
   - "8001:8001"
   
book-service:
  image: ashoksuryap/book-service
  hostname: book-service
  links:
    - service-registry
    - review-service
  environment:
     EUREKA_HOST: service-registry
     EUREKA_PORT: 8001
  ports:
    - "8081:8081"

review-service:
  image: ashoksuryap/review-service
  hostname: review-service
  links:
    - service-registry
  environment:
     EUREKA_HOST: service-registry
     EUREKA_PORT: 8001
  ports:
    - "8082:8082"