version: '2.2'
nextgen-erueka-server:
  image: ashoksuryap/nextgen-erueka-server
  hostname: nextgen-erueka-server
  ports:
   - "8001:8001"
   
nextgen-book-service:
  image: ashoksuryap/nextgen-book-service
  hostname: nextgen-book-service
  links:
    - nextgen-erueka-server
    - nextgen-review-service
  environment:
     EUREKA_HOST: nextgen-erueka-server
     EUREKA_PORT: 8001
  ports:
    - "8081:8081"

nextgen-review-service:
  image: ashoksuryap/nextgen-review-service
  hostname: nextgen-review-service
  links:
    - nextgen-erueka-server
  environment:
     EUREKA_HOST: nextgen-erueka-server
     EUREKA_PORT: 8001
  ports:
    - "8082:8082"