version: '2.2'

services:
  nextgen-eureka-server:
    image: ashoksuryap/nextgen-eureka-server
    hostname: nextgen-eureka-server
    ports:
     - "8001:8001"

  nextgen-book-service:
    image: ashoksuryap/nextgen-book-service
    hostname: nextgen-book-service
    links:
      - nextgen-eureka-server
      - nextgen-reviewservice
    environment:
       EUREKA_HOST: nextgen-eureka-server
       EUREKA_PORT: 8001
    ports:
      - "8081:8081"

  nextgen-reviewservice:
    image: ashoksuryap/nextgen-reviewservice
    hostname: nextgen-reviewservice
    links:
      - nextgen-eureka-server
    environment:
       EUREKA_HOST: nextgen-eureka-server
       EUREKA_PORT: 8001
    ports:
      - "8082:8082"