---
# Define the port where the Service Registry server would be running
server:
  port: 8002

# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8002}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0